name: Compliance Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - '!checkvalgrind**'

jobs:
  compliance:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Run Test
        run: |
          ci/deb/build.sh -s compliance -tp $(pwd)
